// Where the app reads the chain — PUBLISHED build (generated by tools/publish/build-ac-publish.mjs): only the
// SAME-ORIGIN Modulo Worker at /rpc (Alchemy key server-side; ≤20 calls per batch). No other endpoint (CSP connect-src 'self').
export const IS_PROD = true;
export const RPC_URL = '/rpc';
export const MAX_BATCH = 20;
